# Description: This file contains the list of sites that will be used in the program.
list = {
    "google": "https://www.google.com",
    "python": "https://www.python.org",
    "facebook": "https://www.facebook.com",
    "youtube": "https://www.youtube.com",
    "twitter": "https://www.twitter.com",
    "instagram": "https://www.instagram.com",
    "reddit": "https://www.reddit.com",
    "github": "https://www.github.com",
    "wikipedia": "https://www.wikipedia.org",
    "amazon": "https://www.amazon.com",
    "ebay": "https://www.ebay.com",
    "netflix": "https://www.netflix.com",
    "bing": "https://www.bing.com",
    "yahoo": "https://www.yahoo.com",
    "linkedin": "https://www.linkedin.com",
    "pinterest": "https://www.pinterest.com",
    "tumblr": "https://www.tumblr.com",
    "imdb": "https://www.imdb.com",
    "craigslist": "https://www.craigslist.org",
    "walmart": "https://www.walmart.com",
    "espn": "https://www.espn.com",
    "cnn": "https://www.cnn.com",
    "nytimes": "https://www.nytimes.com",
    "weather": "https://www.weather.com",
    "foxnews": "https://www.foxnews.com",
    "msn": "https://www.msn.com",
    "hulu": "https://www.hulu.com",
    "target": "https://www.target.com",
    "bbc": "https://www.bbc.com",
    "paypal": "https://www.paypal.com",
    "apple": "https://www.apple.com",
    "quizlet": "https://www.quizlet.com",
    "zillow": "https://www.zillow.com",
    
}
